### ISSUE TITLE
Score input enhancements

### ISSUE THREAD

**Issue by rlawisch** [eparraga95/dance_fit_scoreboard_front#69]
Phoenix scores, grades and plates are pretty straightforward. The user input for scores could be comprised of only the step grades (perfects, greats, goods, bads and misses) and the stage break, and the application could easily calculate the score, grade and plate (if any, as setting the score as broken would set to none) on the fly.
This would make score input easier and way less time-consuming.

**Comment by eparraga95** [comment]
Adressing this rn, we also need the max_combo input because the formula I found is:

https://x.com/mr_weq/status/1656860777826091008/photo/1

Either we input value to calculate max_combo or vice-versa. I think we`ll have something to show the calculated score to the player as well before the actual submission just to be sure. Grading and Plating should be fine with some ifs and elses too.

Thanks for the feedbacks! <3

**Comment by rlawisch** [comment]
You're right, I forgot about the max combo, good catch!
I agree, having it calculated is easier and less error-prone
